name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.12'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tests with coverage
      run: |
        coverage run -m pytest
        coverage xml
        coverage-badge -o coverage.svg
    - uses: actions/upload-artifact@v4
      with:
        name: coverage-image
        path: coverage.svg

    - name: Setup Git for Pages
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"

    - name: Checkout gh-pages branch

      run: |
        git fetch origin
        git checkout gh-pages || git checkout --orphan gh-pages
        ls -a
        cp coverage.svg .
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Push to gh-pages branch
      run: |
        git add coverage.svg
        git commit -m "Update coverage badge"
        git push origin gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}